"""Create secret table

Revision ID: 377fd15f38fe
Revises: 
Create Date: 2023-06-15 18:31:23.600891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '377fd15f38fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('create extension if not exists "uuid-ossp"'))
    op.create_table('secret',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('secret_key', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('secret', sa.LargeBinary(), nullable=True),
    sa.Column('tag', sa.LargeBinary(), nullable=True),
    sa.Column('use_user_password', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_secret_key'), 'secret', ['secret_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_secret_key'), table_name='secret')
    op.drop_table('secret')
    # ### end Alembic commands ###
